

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: mis_gastos
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: .
    command: ./wait-for-it.sh db 3306 -- python app/main.py
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development

volumes:
  db_data: